### ISSUE TITLE
Missing slash in "act" index creation HTTP PUT.

### ISSUE THREAD

**Issue by dev-239** [mnemonic-no/act-platform#3]
https://github.com/mnemonic-no/act-platform/blob/9ee9fe9f57c41e430b47583a98fdad15f9cfc6a3/dao/src/no/mnemonic/act/platform/dao/elastic/FactSearchManager.java#L381

This call will produce a URL such as "http://localhost:9200act".

More information can be found [here](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/5.6/java-rest-low-usage-requests.html).

**Comment by ko-mueller** [comment]
Hi!

How did you determine that it actually sends "http://localhost:9200act" to Elasticsearch? Have you observed any issues related to this? We haven't seen any problems so far and that component is very well tested. I'd like to confirm that this is an actual problem and not just a cosmetic change.

Kind regards,
Konstantin

**Comment by dev-239** [comment]
I tried to recreate the error, but could not. So i looked into the process of how this happened. When i first started the jar i did not use the correct version of Elasticsearch. This entailed a series of issues. Now i have the correct version installed so i could not reproduce them.

Perhaps the README.md should list explicit versions that should be used. For example for Elasticsearch, state that "5.6.x" should be used.

**Comment by ko-mueller** [comment]
Hi!

Thank you for the quick response! I'm about to upgrade Elasticsearch to a newer version, however, I agree that the required version should be stated in the readme. I'm also planning to write a more elaborate deployment guide.

Anyway, I will close the issue.

Kind regards,
Konstantin
